# Generated by Django 4.2.11 on 2026-01-04 14:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Premium Collection 2026', max_length=100)),
                ('title_line1', models.CharField(default='Discover Your', max_length=100)),
                ('title_line2', models.CharField(default='Signature Scent', max_length=100)),
                ('subtitle', models.TextField(default="Immerse yourself in our curated collection of luxury perfumes, crafted with the world's finest ingredients.")),
                ('cta_primary_text', models.CharField(default='Explore Collection', max_length=50)),
                ('cta_primary_url', models.CharField(default='/shop/', max_length=200)),
                ('cta_secondary_text', models.CharField(default='View Bestsellers', max_length=50)),
                ('cta_secondary_url', models.CharField(default='#featured', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/')),
                ('hero_image_url', models.URLField(blank=True, help_text='External image URL (used if no image uploaded)')),
                ('stat1_value', models.CharField(default='500+', max_length=20)),
                ('stat1_label', models.CharField(default='Premium Scents', max_length=50)),
                ('stat2_value', models.CharField(default='50K+', max_length=20)),
                ('stat2_label', models.CharField(default='Happy Customers', max_length=50)),
                ('stat3_value', models.CharField(default='100%', max_length=20)),
                ('stat3_label', models.CharField(default='Authentic', max_length=50)),
                ('card1_title', models.CharField(default='Free Delivery', max_length=50)),
                ('card1_subtitle', models.CharField(default='Nationwide', max_length=50)),
                ('card1_icon', models.CharField(default='fa-shipping-fast', max_length=50)),
                ('card2_title', models.CharField(default='100% Original', max_length=50)),
                ('card2_subtitle', models.CharField(default='Guaranteed', max_length=50)),
                ('card2_icon', models.CharField(default='fa-certificate', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('featured', 'Featured Products'), ('bestsellers', 'Best Sellers'), ('new_arrivals', 'New Arrivals'), ('categories', 'Shop by Category'), ('banner', 'Promotional Banner'), ('testimonials', 'Testimonials'), ('newsletter', 'Newsletter Signup'), ('custom', 'Custom Content')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.TextField(blank=True)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='cms/banners/')),
                ('banner_url', models.CharField(blank=True, max_length=200)),
                ('banner_button_text', models.CharField(blank=True, max_length=50)),
                ('custom_content', ckeditor.fields.RichTextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('products_to_show', models.IntegerField(default=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Us'), ('contact', 'Contact Us'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions'), ('shipping', 'Shipping Policy'), ('returns', 'Returns Policy'), ('faq', 'FAQ')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('meta_title', models.CharField(blank=True, max_length=100)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('top', 'Top Banner (Announcement Bar)'), ('homepage', 'Homepage Banner'), ('shop', 'Shop Page Banner'), ('sidebar', 'Sidebar Banner')], max_length=20)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('subtext', models.CharField(blank=True, max_length=200)),
                ('background_color', models.CharField(default='#D4AF37', help_text='Hex color code', max_length=7)),
                ('text_color', models.CharField(default='#1a1a2e', help_text='Hex color code', max_length=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/banners/')),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('link_text', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Our Collection', max_length=100)),
                ('page_subtitle', models.TextField(default='Explore our curated selection of luxury perfumes')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='cms/shop/')),
                ('empty_title', models.CharField(default='No products found', max_length=100)),
                ('empty_message', models.TextField(default='Check back later for new arrivals.')),
                ('category_filter_label', models.CharField(default='Categories', max_length=50)),
                ('price_filter_label', models.CharField(default='Price Range', max_length=50)),
                ('sort_label', models.CharField(default='Sort By', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Page Content',
                'verbose_name_plural': 'Shop Page Content',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SceaniCollections', max_length=100)),
                ('site_tagline', models.CharField(default='Luxury Perfumes & Fragrances', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='Used for SEO meta description')),
                ('contact_email', models.EmailField(default='info@sceanicollections.com', max_length=254)),
                ('contact_phone', models.CharField(default='+234 XXX XXX XXXX', max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('business_hours', models.CharField(default='Mon - Sat: 9AM - 6PM', max_length=100)),
                ('footer_text', models.TextField(blank=True, default='Your trusted source for authentic luxury perfumes.')),
                ('copyright_text', models.CharField(default='© 2026 SceaniCollections. All rights reserved.', max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
