# Generated by Django 6.0 on 2026-01-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_paymentmethod'),
        ('store', '0004_newslettersubscriber'),
    ]

    operations = [
    ]
