# Generated by Django 6.0 on 2026-01-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('overview', 'Overview'), ('orders', 'Orders'), ('products', 'Products'), ('customers', 'Customers'), ('analytics', 'Analytics')], default='overview', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('new_order_notifications', models.BooleanField(default=True)),
                ('low_stock_notifications', models.BooleanField(default=True)),
                ('review_notifications', models.BooleanField(default=True)),
                ('items_per_page', models.IntegerField(default=20)),
                ('show_charts', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'New Order'), ('review', 'New Review'), ('inventory', 'Low Inventory'), ('customer', 'Customer Support'), ('system', 'System Alert'), ('payment', 'Payment Received')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=True)),
                ('action_url', models.URLField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('users', models.ManyToManyField(limit_choices_to={'user_type__in': ['admin', 'staff']}, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('sales', 'Sales'), ('orders', 'Orders'), ('customers', 'Customers'), ('products', 'Products'), ('traffic', 'Website Traffic'), ('revenue', 'Revenue')], max_length=20)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date', 'data_type'],
                'unique_together': {('data_type', 'period', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomerDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_recent_orders', models.BooleanField(default=True)),
                ('show_wishlist', models.BooleanField(default=True)),
                ('show_recommendations', models.BooleanField(default=True)),
                ('show_loyalty_points', models.BooleanField(default=True)),
                ('order_updates_email', models.BooleanField(default=True)),
                ('order_updates_sms', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=True)),
                ('review_reminders', models.BooleanField(default=True)),
                ('show_purchase_history', models.BooleanField(default=True)),
                ('allow_profile_view', models.BooleanField(default=False)),
                ('last_viewed_products', models.JSONField(blank=True, default=list)),
                ('recently_searched', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'Order Update'), ('shipment', 'Shipment Update'), ('wishlist', 'Wishlist Update'), ('price_drop', 'Price Drop'), ('back_in_stock', 'Back in Stock'), ('review', 'Review Reminder'), ('loyalty', 'Loyalty Points'), ('marketing', 'Marketing')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('sent_email', models.BooleanField(default=False)),
                ('sent_sms', models.BooleanField(default=False)),
                ('sent_push', models.BooleanField(default=False)),
                ('in_app', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=True)),
                ('action_url', models.URLField(blank=True)),
                ('action_label', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stat', 'Statistic'), ('chart', 'Chart'), ('table', 'Table'), ('list', 'List')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('data_source', models.CharField(help_text='Source of data for widget', max_length=100)),
                ('column', models.IntegerField(default=1)),
                ('row', models.IntegerField(default=1)),
                ('width', models.IntegerField(default=1, help_text='Number of columns widget spans (1-4)')),
                ('height', models.IntegerField(default=1, help_text='Number of rows widget spans (1-4)')),
                ('refresh_interval', models.IntegerField(default=300, help_text='Refresh interval in seconds')),
                ('is_visible', models.BooleanField(default=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['column', 'row'],
            },
        ),
    ]
